### ISSUE TITLE
404 for picturefill.js

### ISSUE THREAD

**Issue by kgardnr** [coralproject/coralproject-site-2016#73]
Hey @OliverM, I'm seeing this error locally. Any idea what picturefill.js does or if we need it?

I see this in the console:

`http://localhost:4000/picturefill.js Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by kgardnr** [comment]
I see the same on staging too actually.

**Comment by OliverM** [comment]
Hmmm, picturefill.js is a polyfill to help ie9 and above understand the ```<picture>``` element, used int he site to present different splash images based on the screen type. If it's not being loaded then the site is probably showing the mobile splash images on desktop in ie. But it looks like the current picturefill.js is some sort of webpage, which makes no sense. I've fixed it locally, would pushing to master disrupt anything you're working on?

**Comment by OliverM** [comment]
Hey @kgardnr I made a new picturefill branch with the needed changes, if you want to merge it into master when ready
