### ISSUE TITLE
Need to create Open Graph Protocol for FB, Twitter sharing our site

### ISSUE THREAD

**Issue by losowsky** [coralproject/coralproject-site-2016#80]
https://developers.facebook.com/docs/sharing/opengraph

**Comment by losowsky** [comment]
Currently looks like this: 

![screen shot 2016-08-31 at 3 44 17 pm](https://cloud.githubusercontent.com/assets/10014755/18143835/cd0b7f82-6f91-11e6-8cc7-7cf52eaa62b3.png)

**Comment by losowsky** [comment]
Also: https://moz.com/blog/meta-data-templates-123

**Comment by kgardnr** [comment]
Completed.
